apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.100-192.168.99.105
    - name: ftps_range
      protocol: layer2
      addresses:
      - 192.168.99.101-192.168.99.101
    - name: wp_range
      protocol: layer2
      addresses:
      - 192.168.99.102-192.168.99.102
    - name: pma_range
      protocol: layer2
      addresses:
      - 192.168.99.103-192.168.99.103