apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  userpass: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  name: phpma-secret
type: Opaque
data:
  dbpassword: bWFuZG8=
  userpass: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  admin_pass: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secret
type: Opaque
data:
  influxdb_database: influxdb
  influxdb_url: http://influxdb:8086
  influxdb_username: grogu
  influxdb_userpass: bWFuZG8=