apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  userpass: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  name: pma-secret
type: Opaque
data:
  userpass: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  WP_PASS: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: influxdb
  name: influxdb-secret
type: Opaque
data:
  influxdb_userpass: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: telegraf
  name: telegraf-secret
type: Opaque
data:
  influxdb_userpass: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  admin_pass: YWRtaW4=