apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  userpass: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  admin_pass: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: pma-secret
type: Opaque
data:
  userpass: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  WP_PASS: bWFuZG8=
---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secret
type: Opaque
data:
  influxdb_database: influxdb
  influxdb_url: http://influxdb:8086
  influxdb_username: grogu
  influxdb_userpass: bWFuZG8=