{
 "title": "Nginx metrics",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Service creation Date / Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "kubernetes_service",
     "query": "SELECT \"created\"/1000000 FROM \"kubernetes_service\" WHERE (\"service_name\" = 'nginx') AND $timeFilter",
     "select": [
      [
       { "params": [ "created" ], "type": "field" },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "Available replicas",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_deployment",
     "select": [
      [
       { "params": [ "replicas_available" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deployment_name", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "Available ports",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Port",
     "groupBy": [
      { "params": [ "port_name" ], "type": "tag" }
     ],
     "measurement": "kubernetes_service",
     "select": [
      [
       { "params": [ "port" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  }
 ]
}