{
 "title": "Telegraf metrics",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Service creation Date / Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "kubernetes_deployment",
     "query": "SELECT \"created\"/1000000 FROM \"kubernetes_service\" WHERE (\"service_name\" = 'telegraf') AND $timeFilter",
     "select": [
      [
       { "params": [ "created" ], "type": "field" },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deployment_name", "operator": "=", "value": "telegraf" }
     ]
    }
   ]
  },
  {
   "title": "Available replicas",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_deployment",
     "select": [
      [
       { "params": [ "replicas_available" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "deployment_name", "operator": "=", "value": "telegraf" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage system",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent", "label": "Usage percentage" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "query": "SELECT \"restarts_total\" FROM \"kubernetes_pod_container\" WHERE (\"container_name\" = 'telegraf') AND $timeFilter GROUP BY \"container_name\"",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu0" }
     ]
    }
   ]
  }
 ]
}