apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: my_nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
      restartPolicy: Always #pod always restarts in the event of a crash, check this
---
apiVersion: v1
kind: Service
metadata:
  annotations:
      metallb.universe.tf/allow-shared-ip: shared ##check purpose of this
  name: nginx
  labels:
      app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: ssh
    port: 22
  - name: http
    port: 80
  - name: https
    port: 443
  type: LoadBalancer